### ISSUE TITLE
Try on another dataset

### ISSUE THREAD

**Issue by phuocnguyen2008** [XYZach/RLSSS#1]
Hi authors, thank you for the amazing work!
I am using your repo to train on another dataset (OCT images) but the results are quite bad. The student model cannot learn anything from the teacher model and performs very badly. Besides it, the teacher model seem to be affected by the student model and eventually performs worse than the initial teacher model. I used U-Net for this experiment.
Do you experience this and have any reasons?
Thank you.
![image](https://user-images.githubusercontent.com/34409468/142093243-7cb7d7b7-7944-4c8f-8141-8a38ca8a9812.png)
Figure 1. Initial results of teacher and student models
![image](https://user-images.githubusercontent.com/34409468/142093205-dab344be-69a8-4243-a103-a38d3518a264.png)
Figure 2. Results after 100 epochs.

**Comment by ryandok** [comment]
@phuocnguyen2008 
Thanks for using it.
How many labeled data do you have? What is the result of training with only labeled data?

**Comment by phuocnguyen2008** [comment]
Thank you for your reply,
I fixed the problem, it's due to my mistake when I print the output.
But I have another concern regarding your implementation.
You use many loss on both labeled and unlabeled set to update teacher model but you dont mention in the paper.
![image](https://user-images.githubusercontent.com/34409468/142973855-17fcdad7-cd3d-4ec6-a0aa-09c3a4a9cb7b.png)
Can you explain about it in the figure attached?
Thank you.

**Comment by Abner228** [comment]
Hi,
As in the paper (12), We did use gradients of many losses to compute the gradients of feedback loss, but optimizer didn't step for those losses.
Hope this helps.
Best
