### ISSUE TITLE
Simply Copy and Paste (w/o cite) for the Meta Pseudo Label cvpr 2022

### ISSUE THREAD

**Issue by Sun-Rider** [XYZach/RLSSS#2]
Hi,

Could you please explain what's the difference between your approach and meta-pseudo label (https://openaccess.thecvf.com/content/CVPR2021/papers/Pham_Meta_Pseudo_Labels_CVPR_2021_paper.pdf), as I don't find the related reference appear in the paper?

Cheers

**Comment by Abner228** [comment]
Hi,
Thanks for your concern to our paper. We are trying to alleviate the problem of semi-supervised medical image segmentation. We found that the mean teacher models are effective solutions for this problem. Based on teacher-student setting, we’d like to optimize both models through gradient descent algorithm. We did follow the work (the earliest arXiv version) you mentioned, which is an amazing work. It's our fault not cite this paper. There are several differences: we focus on volumetric segmentation while they do classification; the calculation of the teacher’s gradient is different.
Hope this helps.
Best

**Comment by Sun-Rider** [comment]
No!  **YOU JUST SIMPLY COPY AND PASTE**, for the entire approach and even the mathematical analysis in your paper.  **YOU DIDN'T EVEN CHANGE THE SYMBOL!** 
**_Your Section 2.2:_**
![image](https://user-images.githubusercontent.com/33716428/145736762-11322010-c84f-42d8-adff-c7d3b84c2d32.png)
![image](https://user-images.githubusercontent.com/33716428/145736934-df9accba-5488-4059-b229-1d486c0c6f11.png)

**_The original paper:_**
![image](https://user-images.githubusercontent.com/33716428/145736792-bf59e911-4c73-48ea-9170-23d65e6e1811.png)
![image](https://user-images.githubusercontent.com/33716428/145736734-a9c583ee-dd9a-4f2e-96b1-c63739e80e7c.png)

How dare you think changing the task from classification to segmentation can be a novelty?  
Besides, I don't see any different calculations. You just follow their pseudo-code that appear in the supplementary file. 

Shame on you guys. I'm wondering whether wangyi knows it or not.
